"""Human-readable descriptions for the 166 MACCS keys.

Two layers per key:

- ``OFFICIAL`` \u2014 the terse MDL/MayaChemTools definition (authoritative, but
  written in domain shorthand: ``A`` = any atom, ``Q`` = heteroatom, ``X`` =
  halogen, ``$`` = ring bond, ``!`` = chain bond, ``%`` = aromatic bond, ``~`` =
  single-or-double). Source: MayaChemTools MACCSKeys documentation (Ref 45-47),
  which reproduces the published key list.
- ``PLAIN`` \u2014 a plain-English translation for the keys a reader is likely to
  hit, so the notebook can explain a bit at a glance without anyone parsing a
  SMARTS string. Falls back to the official text when no translation exists.

The goal is teaching intuition, not perfect IUPAC phrasing; where the official
key is already readable (e.g. "OH", "AROMATIC RING") we keep it.
"""

from __future__ import annotations

# Legend for the shorthand used in the official MACCS definitions.
SHORTHAND_LEGEND: dict[str, str] = {
    "A": "any atom",
    "Q": "heteroatom (any non-C, non-H atom)",
    "X": "halogen (F, Cl, Br, I)",
    "Z": "an exotic atom (not H, C, N, O, Si, P, S, or a halogen)",
    "$": "a ring bond",
    "!": "a chain (non-ring) bond",
    "%": "an aromatic bond",
    "~": "a single or double bond",
    "@1": "ring closure back to the first atom",
}


# Official terse definitions, key 1..166 (MayaChemTools / MDL numbering).
OFFICIAL: dict[int, str] = {
    1: "ISOTOPE", 2: "103 < ATOMIC NO. < 256", 3: "GROUP IVA,VA,VIA PERIODS 4-6 (Ge...)",
    4: "ACTINIDE", 5: "GROUP IIIB,IVB (Sc...)", 6: "LANTHANIDE", 7: "GROUP VB,VIB,VIIB (V...)",
    8: "QAAA@1", 9: "GROUP VIII (Fe...)", 10: "GROUP IIA (ALKALINE EARTH)", 11: "4M RING",
    12: "GROUP IB,IIB (Cu...)", 13: "ON(C)C", 14: "S-S", 15: "OC(O)O", 16: "QAA@1", 17: "CTC",
    18: "GROUP IIIA (B...)", 19: "7M RING", 20: "SI", 21: "C=C(Q)Q", 22: "3M RING", 23: "NC(O)O",
    24: "N-O", 25: "NC(N)N", 26: "C$=C($A)$A", 27: "I", 28: "QCH2Q", 29: "P", 30: "CQ(C)(C)A",
    31: "QX", 32: "CSN", 33: "NS", 34: "CH2=A", 35: "GROUP IA (ALKALI METAL)", 36: "S HETEROCYCLE",
    37: "NC(O)N", 38: "NC(C)N", 39: "OS(O)O", 40: "S-O", 41: "CTN", 42: "F", 43: "QHAQH",
    44: "OTHER", 45: "C=CN", 46: "BR", 47: "SAN", 48: "OQ(O)O", 49: "CHARGE", 50: "C=C(C)C",
    51: "CSO", 52: "NN", 53: "QHAAAQH", 54: "QHAAQH", 55: "OSO", 56: "ON(O)C", 57: "O HETEROCYCLE",
    58: "QSQ", 59: "Snot%A%A", 60: "S=O", 61: "AS(A)A", 62: "A$A!A$A", 63: "N=O", 64: "A$A!S",
    65: "C%N", 66: "CC(C)(C)A", 67: "QS", 68: "QHQH (&...)", 69: "QQH", 70: "QNQ", 71: "NO",
    72: "OAAO", 73: "S=A", 74: "CH3ACH3", 75: "A!N$A", 76: "C=C(A)A", 77: "NAN", 78: "C=N",
    79: "NAAN", 80: "NAAAN", 81: "SA(A)A", 82: "ACH2QH", 83: "QAAAA@1", 84: "NH2", 85: "CN(C)C",
    86: "CH2QCH2", 87: "X!A$A", 88: "S", 89: "OAAAO", 90: "QHAACH2A", 91: "QHAAACH2A",
    92: "OC(N)C", 93: "QCH3", 94: "QN", 95: "NAAO", 96: "5M RING", 97: "NAAAO", 98: "QAAAAA@1",
    99: "C=C", 100: "ACH2N", 101: "8M RING", 102: "QO", 103: "CL", 104: "QHACH2A",
    105: "A$A($A)$A", 106: "QA(Q)Q", 107: "XA(A)A", 108: "CH3AAACH2A", 109: "ACH2O", 110: "NCO",
    111: "NACH2A", 112: "AA(A)(A)A", 113: "Onot%A%A", 114: "CH3CH2A", 115: "CH3ACH2A",
    116: "CH3AACH2A", 117: "NAO", 118: "ACH2CH2A > 1", 119: "N=A", 120: "HETEROCYCLIC ATOM > 1 (&...)",
    121: "N HETEROCYCLE", 122: "AN(A)A", 123: "OCO", 124: "QQ", 125: "AROMATIC RING > 1",
    126: "A!O!A", 127: "A$A!O > 1 (&...)", 128: "ACH2AAACH2A", 129: "ACH2AACH2A", 130: "QQ > 1 (&...)",
    131: "QH > 1", 132: "OACH2A", 133: "A$A!N", 134: "X (HALOGEN)", 135: "Nnot%A%A", 136: "O=A > 1",
    137: "HETEROCYCLE", 138: "QCH2A > 1 (&...)", 139: "OH", 140: "O > 3 (&...)", 141: "CH3 > 2 (&...)",
    142: "N > 1", 143: "A$A!O", 144: "Anot%A%Anot%A", 145: "6M RING > 1", 146: "O > 2",
    147: "ACH2CH2A", 148: "AQ(A)A", 149: "CH3 > 1", 150: "A!A$A!A", 151: "NH", 152: "OC(C)C",
    153: "QCH2A", 154: "C=O", 155: "A!CH2!A", 156: "NA(A)A", 157: "C-O", 158: "C-N", 159: "O > 1",
    160: "CH3", 161: "N", 162: "AROMATIC", 163: "6M RING", 164: "O", 165: "RING", 166: "FRAGMENTS",
}


# Plain-English translations for the keys most likely to be encountered. Written
# for intuition. Anything not here falls back to the official definition.
PLAIN: dict[int, str] = {
    1: "Isotope label present (rarely used; effectively never fires)",
    2: "Contains a heavy element (atomic number 104-255)",
    4: "Contains an actinide element",
    6: "Contains a lanthanide element",
    11: "Has a 4-membered ring",
    13: "An N(C)C bonded to an oxygen (e.g. an N-oxide / hydroxylamine motif)",
    14: "Has a sulfur-sulfur bond (disulfide)",
    15: "A carbon bonded to three oxygens (e.g. carbonate-like)",
    19: "Has a 7-membered ring",
    20: "Contains silicon",
    22: "Has a 3-membered ring (e.g. epoxide, cyclopropane)",
    23: "A nitrogen on a carbon that also carries two oxygens (carbamate-like)",
    24: "Has a nitrogen-oxygen single bond",
    25: "A carbon bonded to three nitrogens (guanidine-like)",
    27: "Contains iodine",
    28: "A CH2 flanked by two heteroatoms",
    29: "Contains phosphorus",
    31: "A heteroatom bonded to a halogen",
    32: "A carbon-sulfur-nitrogen chain",
    33: "A nitrogen-sulfur bond",
    36: "Sulfur that is part of a ring (thiophene-like); note: NOT sulfur on a side chain",
    37: "A urea-like N-C(=O)-N motif",
    39: "A sulfur bonded to three oxygens (sulfonate-like)",
    40: "A sulfur-oxygen single bond",
    42: "Contains fluorine",
    44: "Some other structural feature (catch-all key)",
    45: "A vinyl group attached to nitrogen (enamine-like)",
    46: "Contains bromine",
    49: "Carries a formal charge",
    52: "Has a nitrogen-nitrogen bond",
    55: "Sulfur bonded to two oxygens (sulfone/sulfoxide fragment)",
    57: "An oxygen that is part of a ring (e.g. furan, pyran)",
    60: "A sulfur double-bonded to oxygen (S=O)",
    63: "A nitrogen double-bonded to oxygen (nitroso/nitro fragment)",
    71: "A nitrogen-oxygen bond",
    77: "Nitrogen-any atom-nitrogen (two N's separated by one atom)",
    78: "A carbon double-bonded to nitrogen (imine)",
    79: "Two nitrogens separated by two atoms",
    80: "Two nitrogens separated by three atoms",
    84: "A primary amine (NH2)",
    85: "A trialkyl amine, N(C)(C)C",
    88: "Contains sulfur (anywhere)",
    92: "An amide-like O-C(-N)-C",
    94: "A heteroatom bonded to nitrogen",
    96: "Has a 5-membered ring",
    99: "Has a carbon-carbon double bond",
    101: "Has an 8-membered ring",
    103: "Contains chlorine",
    110: "An amide backbone: N-C=O",
    117: "Nitrogen-any atom-oxygen",
    118: "Two separate ethylene (-CH2-CH2-) units",
    120: "More than one heteroatom sits in a ring",
    121: "Nitrogen that is part of a ring (e.g. pyridine, pyrrole)",
    123: "An acetal/ether-ester O-C-O motif",
    125: "Has more than one aromatic ring",
    131: "More than one heteroatom bearing a hydrogen (e.g. multiple OH/NH)",
    134: "Contains a halogen (F, Cl, Br, or I)",
    136: "More than one C=O or similar double bond to oxygen",
    137: "Has a heterocycle (a ring containing a non-carbon atom)",
    139: "Has a hydroxyl group (-OH)",
    140: "More than 3 oxygen atoms",
    141: "More than 2 methyl groups",
    142: "More than one nitrogen",
    145: "More than one 6-membered ring",
    146: "More than 2 oxygen atoms",
    147: "An ethylene bridge (-CH2-CH2-) between two atoms",
    149: "More than one methyl group",
    151: "Has an N-H",
    152: "An ether/alcohol-like O-C(-C)-C",
    154: "Has a carbonyl (C=O)",
    157: "Has a carbon-oxygen single bond (alcohol/ether)",
    158: "Has a carbon-nitrogen single bond (amine)",
    159: "More than one oxygen",
    160: "Has a methyl group (CH3)",
    161: "Contains nitrogen",
    162: "Has an aromatic atom",
    163: "Has a 6-membered ring",
    164: "Contains oxygen",
    165: "Is (or has) a ring",
    166: "Made of more than one disconnected fragment (e.g. a salt)",
    # --- remaining keys, translated from the official shorthand ---
    3: "Contains a heavier group IV/V/VI element (Ge, As, Se, Sn...)",
    5: "Contains an early transition metal (Sc, Ti, Y, Zr...)",
    7: "Contains a group V-VII transition metal (V, Cr, Mn...)",
    8: "A heteroatom in a ring, three atoms from a ring-closure (Q-A-A-A ring)",
    9: "Contains a group VIII metal (Fe, Co, Ni, Ru...)",
    10: "Contains an alkaline-earth metal (Mg, Ca...)",
    12: "Contains a coinage/zinc-group metal (Cu, Zn, Ag...)",
    16: "A heteroatom two atoms from a ring-closure (Q-A-A ring)",
    17: "A carbon triple-bonded to another carbon (alkyne)",
    18: "Contains a group IIIA element (B, Al, Ga...)",
    21: "A carbon double-bonded to a carbon carrying two heteroatoms",
    26: "A ring C=C where both carbons carry a ring substituent",
    30: "A carbon bearing a heteroatom, two carbons and one more atom (quaternary-ish)",
    34: "A terminal =CH2 (methylene) double-bonded to something",
    35: "Contains an alkali metal (Li, Na, K...)",
    38: "A carbon flanked by two nitrogens with a methyl branch (amidine-like)",
    41: "A carbon triple-bonded to nitrogen (nitrile)",
    43: "Two H-bearing heteroatoms separated by one atom (e.g. HO-C-OH)",
    47: "A sulfur-any atom-nitrogen chain",
    48: "An oxygen on a carbon-like center carrying two more oxygens",
    50: "An isopropenyl-like C=C(C)C",
    51: "A carbon-sulfur-oxygen chain",
    53: "Two H-bearing heteroatoms separated by three atoms",
    54: "Two H-bearing heteroatoms separated by two atoms",
    56: "An N(O)C bonded to a second oxygen (nitro/N-oxide-like)",
    58: "A sulfur flanked by two heteroatoms (Q-S-Q)",
    59: "A sulfur attached to a non-aromatic chain",
    61: "A sulfur with three atom neighbors (sulfoxide/sulfone core)",
    62: "A ring atom joined by a chain bond to another ring (ring-chain-ring)",
    64: "A ring atom linked by a chain bond to a sulfur",
    65: "An aromatic carbon-nitrogen bond",
    66: "A tert-butyl-like carbon: C bonded to three carbons and one more atom",
    67: "A heteroatom bonded to sulfur",
    68: "More than one pair of adjacent H-bearing heteroatoms",
    69: "A heteroatom bonded to an H-bearing heteroatom",
    70: "A nitrogen flanked by two heteroatoms (Q-N-Q)",
    72: "Two oxygens separated by two atoms (O-A-A-O)",
    73: "A sulfur double-bonded to any atom (S=A)",
    74: "Two methyls on the same central atom (CH3-A-CH3)",
    75: "A nitrogen at a chain/ring boundary",
    76: "A carbon double-bonded to a carbon with two substituents",
    81: "A sulfur with three atom neighbors",
    82: "A CH2 next to both any-atom and an H-bearing heteroatom",
    83: "A heteroatom four atoms from a ring-closure (large ring/heteroatom)",
    86: "A heteroatom flanked by two CH2 groups (CH2-Q-CH2)",
    87: "A halogen on a chain bond next to a ring",
    89: "Two oxygens separated by three atoms (O-A-A-A-O)",
    90: "An H-bearing heteroatom two atoms from a CH2",
    91: "An H-bearing heteroatom three atoms from a CH2",
    93: "A methyl attached to a heteroatom (Q-CH3)",
    95: "A nitrogen and an oxygen separated by two atoms",
    97: "A nitrogen and an oxygen separated by three atoms",
    98: "A heteroatom five atoms from a ring-closure (six-membered heteroatom ring)",
    100: "A CH2 bridging any atom and a nitrogen",
    102: "A heteroatom bonded to oxygen",
    104: "An H-bearing heteroatom bonded via a CH2 to any atom",
    105: "A ring atom with three ring bonds (ring fusion/branch point)",
    106: "A central heteroatom with two heteroatom neighbors",
    107: "A halogen on an atom with two more substituents",
    108: "A methyl three atoms from a CH2 group",
    109: "A CH2 bridging any atom and an oxygen",
    111: "A CH2 bridging a nitrogen and any atom",
    112: "A highly-branched atom (bonded to four other atoms)",
    113: "An oxygen attached to a non-aromatic chain",
    114: "An ethyl group (CH3-CH2-) attached to something",
    115: "A methyl two atoms from a CH2",
    116: "A methyl three atoms from a CH2",
    119: "A nitrogen double-bonded to any atom (N=A)",
    122: "A trisubstituted nitrogen, N(A)(A)A",
    124: "Two heteroatoms bonded together (Q-Q)",
    126: "An oxygen bridging two atoms by chain bonds (chain ether)",
    127: "More than one ring atom joined by a chain bond to an oxygen",
    128: "Two CH2 groups separated by three atoms",
    129: "Two CH2 groups separated by two atoms",
    130: "More than one pair of bonded heteroatoms",
    132: "An oxygen two atoms from a CH2 group",
    133: "A ring atom linked by a chain bond to a nitrogen",
    135: "A nitrogen attached to a non-aromatic chain",
    138: "More than one CH2 next to a heteroatom",
    143: "A ring atom linked by a chain bond to an oxygen (e.g. ring-OH)",
    144: "An atom at an aromatic/non-aromatic boundary",
    148: "A heteroatom with three atom neighbors",
    150: "A chain-ring-chain atom sequence (ring flanked by chain bonds)",
    153: "A CH2 bridging a heteroatom and any atom",
    155: "A CH2 flanked by two chain bonds (isolated methylene)",
    156: "A nitrogen with three atom neighbors, N(A)(A)A",
}


def official(bit: int) -> str:
    """The terse authoritative MACCS definition for a key."""
    return OFFICIAL.get(bit, f"key {bit}")


def plain(bit: int) -> str:
    """Plain-English description, falling back to the official definition."""
    if bit in PLAIN:
        return PLAIN[bit]
    return OFFICIAL.get(bit, f"key {bit}")
